---
name: '[RMV] Takedown request'
description: Request the removal of an existing swag opportunity entry.
title: '[RMV] Takedown request'
assignees:
  - SoftCreatR
  - benbarth
labels:
  - takedown
body:
  - type: markdown
    attributes:
      value: >-
        Sad to see you go, but we respect your decision and will remove the
        listing as quickly as possible. Please complete the form below and we
        will get back to you shortly.


        __Please note that takedown requests are only accepted from authorized
        representatives. Requests without valid proof will be closed without
        further notice.__
  - type: input
    id: org
    attributes:
      label: Organization
      description: Name of the organization you represent.
      placeholder: Acme Corporation
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why should this swag listing be removed?
      placeholder: The organization no longer offers a Hacktoberfest reward.
    validations:
      required: true
  - type: textarea
    id: proof
    attributes:
      label: Proof Of Ownership
      description: Evidence that shows you are authorized to make this request.
      placeholder: >-
        ![authorized-representative](https://user-images.githubusercontent.com/81188/138868923-c66aca01-43de-4f2b-a676-208b92229af5.jpg)
    validations:
      required: true
