---
name: "[UPD] Update existing swag opportunity"
description: Share changes to an existing swag opportunity entry.
title: "[UPD] Update existing swag opportunity"
labels:
  - enhancement
  - help wanted
body:
  - type: input
    id: org
    attributes:
      label: Organization
      description: Name of the organization offering this swag.
      placeholder: Acme Corporation
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Organization Website
      description: Website URL of the organization.
      placeholder: https://www.acme.example
    validations:
      required: true
  - type: input
    id: announcement
    attributes:
      label: Announcement URL
      description: >-
        Link to the announcement confirming the organization's Hacktoberfest
        participation (for example a blog post, GitHub issue, or community
        update).
      placeholder: https://blog.acme.example/hacktoberfest
  - type: textarea
    id: desc
    attributes:
      label: Description / summary
      description: >-
        Summarize what changed about the swag items or contribution
        requirements.
      placeholder: Update the number of required merged pull requests.
    validations:
      required: true
  - type: checkboxes
    id: swaglist
    attributes:
      label: Swag items
      description: Select all swag items being offered after the update.
      options:
        - label: Glasses
        - label: Laptop
        - label: Mug
        - label: Shirt
        - label: Socks
        - label: Stickers
        - label: Trees
        - label: Other
