---
name: Update Contributors

on: [ push, workflow_dispatch]

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - uses: BobAnkh/add-contributors@master
        with:
          REPO_NAME: 'benbarth/hacktoberfest-swag'
          CONTRIBUTOR: '## Contributors ✨'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
